### ISSUE TITLE
出现 Unsupported proxy mode redirect 以及 permission denied

### ISSUE THREAD

**Issue by RunningMelos** [Kr328/ClashForMagisk#4]
设备是 `小米9 MIUI11 安卓10`，无法正常使用，问题不知道在哪，同样的配置在clash for windows 上没有问题，具体 LOG 附在后文，辛苦啦~
当前 `{InternalStorage}/Android/data/com.github.kr328.clash` 目录为
```log
config.yaml
Country.mmdb
starter.yaml (已设置为 mode: redirect )
RUNNING
mode.d
    proxy-only
        on-start.sh
        on-stop.sh
    redirect
        on-start.sh
        on-stop.sh
```
`config.yaml` 内部分内容为
```yaml
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
secret: ""
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
    - 223.5.5.5
  fallback: 
    - tls://dns.rubyfish.cn:853
```
所抓取的 LOG
```
%TIME%  4346  4703 D Clash   : Control Directory Changed START
%TIME%  4346  4703 E Clash   : Unsupported proxy mode redirect
%TIME%  4346  4703 D Clash   : Starting clash /dev/clash_root/core/setuidgid 1001 1001 3003,1015 /dev/clash_root/core/clash -d /sdcard/Android/data/com.github.kr328.clash 2>&1
%TIME%  4346  4703 I Clash   : Clash started
%TIME%  4346 17626 I Clash   : time=%TIME% level=error msg="Start DNS server error: listen udp 0.0.0.0:53: bind: permission denied"
%TIME%  4346 17626 I Clash   : time=%TIME% level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
%TIME%  4346 17626 I Clash   : time=%TIME% level=info msg="Redir proxy listening at: 127.0.0.1:7892"
%TIME%  4346 17626 I Clash   : time=%TIME% level=info msg="RESTful API listening at: 127.0.0.1:9090"
%TIME%  4346 17626 I Clash   : time=%TIME% level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
%TIME%  4346  4703 D Clash   : Control Directory Changed RUNNING
```
